version: '3'
services:
    app:
        build: .
        expose:
            - "5223"
            - "80"
        restart: unless-stopped
        ports:
            - "5223:80"
        volumes:
            - ./src:/srv/app/8068_metrics_client/src
            - ./public:/srv/app/8068_metrics_client/public
        command: [ "npm", "server.js" ]
